### PR TITLE
Added files via upload

### PR DESCRIPTION
**Pull request by gprieck**
Stream Support for ShapefileDataReader using IStreamProviderRegistry 
Issue #91

### CODE REVIEW

**Comment by gprieck** [comment]
Another developer from our company (Premier Crop Systems) put together this version using everyone's suggestions.  In our tests it works for both the ShapefileDataWriter and the ShapefileDataReader.  

public static void Example_ShapefileDataWriter()
        {
            IList<IFeature> featureCollection = new List<IFeature>();

            IGeometry pt1 = new Point(-106.6764794, 35.0824099);
            AttributesTable table1 = new AttributesTable();
            table1.AddAttribute("ID", "1");
            table1.AddAttribute("Name", "George");
            Feature f1 = new Feature(pt1, table1);
            featureCollection.Add(f1);

            IGeometry pt2 = new Point(-106.6764794, 35.0824099);
            AttributesTable table2 = new AttributesTable();
            table2.AddAttribute("ID", "2");
            table2.AddAttribute("Name", "Cabe");
            Feature f2 = new Feature(pt2, table2);
            featureCollection.Add(f2);

            ByteStreamProvider shpProvider = new ByteStreamProvider(StreamTypes.Shape);
            ByteStreamProvider shxProvider = new ByteStreamProvider(StreamTypes.Index);
            ByteStreamProvider dbfProvider = new ByteStreamProvider(StreamTypes.Data);

            GeometryFactory factory = new GeometryFactory();

            ShapefileByteStreamProviderRegistry r = new ShapefileByteStreamProviderRegistry(shpProvider, dbfProvider, shxProvider);

            ShapefileDataWriter dataWriter = new ShapefileDataWriter(r, factory, Encoding.GetEncoding(1252));

            dataWriter.Header = ShapefileDataWriter.GetHeader(featureCollection[0] as IFeature, featureCollection.Count);
            dataWriter.Write(featureCollection);

            File.WriteAllBytes(@"c:\temp\C.shp", shpProvider.StoredBytes);
            File.WriteAllBytes(@"c:\temp\C.shx", shxProvider.StoredBytes);
            File.WriteAllBytes(@"c:\temp\C.dbf", dbfProvider.StoredBytes);
        }
        public static void Example_ShapefileDataReader()
        {
            byte[] shpBytes = File.ReadAllBytes(@"c:\temp\C.shp");
            byte[] shxBytes = File.ReadAllBytes(@"c:\temp\C.shx");
            byte[] dbfBytes = File.ReadAllBytes(@"c:\temp\C.dbf");

            ByteStreamProvider shpProvider = new ByteStreamProvider(StreamTypes.Shape,shpBytes);
            ByteStreamProvider shxProvider = new ByteStreamProvider(StreamTypes.Index,shxBytes);
            ByteStreamProvider dbfProvider = new ByteStreamProvider(StreamTypes.Data,dbfBytes);

            GeometryFactory factory = new GeometryFactory();

            ShapefileByteStreamProviderRegistry r = new ShapefileByteStreamProviderRegistry(shpProvider, dbfProvider, shxProvider);
            ShapefileDataReader shapeFileDataReader = new ShapefileDataReader(r, factory);
)

[ByteStreamProvider.txt](https://github.com/gprieck/NetTopologySuite/files/163796/ByteStreamProvider.txt)
[ShapefileByteStreamProviderRegistry.txt](https://github.com/gprieck/NetTopologySuite/files/163797/ShapefileByteStreamProviderRegistry.txt)

**Comment by FObermaier** [comment]
What is so special about `ShapefileByteStreamProviderRegistry`?

Wouldn't it make more sense to add `IDisposable` to `IStreamProviderRegistry` and `IStreamProvider` as most Streams implement `IDisposable` as well. Thus "standard" ShapefileStreamProviderRegistry would benefit, too.

Or am I missing something?

**Comment by FObermaier** [comment]
Having looked at it further I'm wondering why ByteStreamProvider is IDisposable in the first place.
Do we need to dispose the array?

**Comment by gprieck** [comment]
Hi Felix,
I am sorry, I let this issue get stale, but I would still like to get it
working.  I am not sure which code you are looking at.  I

jaundice <https://github.com/jaundice> has a patch from March 15.  I can't
get that patch applied, so I would appreciate some help getting the patch
applied.

*George*

**Pull request merged**
